/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginCommand"];
                    "text/json": components["schemas"]["LoginCommand"];
                    "application/*+json": components["schemas"]["LoginCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResult"];
                        "application/json": components["schemas"]["LoginResult"];
                        "text/json": components["schemas"]["LoginResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerAccountId}/boats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerAccountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDto"][];
                        "application/json": components["schemas"]["BoatDto"][];
                        "text/json": components["schemas"]["BoatDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerAccountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBoatRequest"];
                    "text/json": components["schemas"]["CreateBoatRequest"];
                    "application/*+json": components["schemas"]["CreateBoatRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBoatRequest"];
                    "text/json": components["schemas"]["UpdateBoatRequest"];
                    "application/*+json": components["schemas"]["UpdateBoatRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerAccountDto"][];
                        "application/json": components["schemas"]["CustomerAccountDto"][];
                        "text/json": components["schemas"]["CustomerAccountDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCustomerAccountCommand"];
                    "text/json": components["schemas"]["CreateCustomerAccountCommand"];
                    "application/*+json": components["schemas"]["CreateCustomerAccountCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CustomerAccountDto"];
                        "application/json": components["schemas"]["CustomerAccountDto"];
                        "text/json": components["schemas"]["CustomerAccountDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCustomerRequest"];
                    "text/json": components["schemas"]["UpdateCustomerRequest"];
                    "application/*+json": components["schemas"]["UpdateCustomerRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marinas/{marinaId}/docks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    marinaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DockDto"][];
                        "application/json": components["schemas"]["DockDto"][];
                        "text/json": components["schemas"]["DockDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    marinaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDockRequest"];
                    "text/json": components["schemas"]["CreateDockRequest"];
                    "application/*+json": components["schemas"]["CreateDockRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDockRequest"];
                    "text/json": components["schemas"]["UpdateDockRequest"];
                    "application/*+json": components["schemas"]["UpdateDockRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marinas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MarinaDto"][];
                        "application/json": components["schemas"]["MarinaDto"][];
                        "text/json": components["schemas"]["MarinaDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMarinaCommand"];
                    "text/json": components["schemas"]["CreateMarinaCommand"];
                    "application/*+json": components["schemas"]["CreateMarinaCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marinas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MarinaDto"];
                        "application/json": components["schemas"]["MarinaDto"];
                        "text/json": components["schemas"]["MarinaDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMarinaRequest"];
                    "text/json": components["schemas"]["UpdateMarinaRequest"];
                    "application/*+json": components["schemas"]["UpdateMarinaRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slip-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    slipId?: string;
                    customerAccountId?: string;
                    activeOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlipAssignmentDto"][];
                        "application/json": components["schemas"]["SlipAssignmentDto"][];
                        "text/json": components["schemas"]["SlipAssignmentDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSlipAssignmentCommand"];
                    "text/json": components["schemas"]["CreateSlipAssignmentCommand"];
                    "application/*+json": components["schemas"]["CreateSlipAssignmentCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slip-assignments/{id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EndAssignmentRequest"];
                    "text/json": components["schemas"]["EndAssignmentRequest"];
                    "application/*+json": components["schemas"]["EndAssignmentRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marinas/{marinaId}/slips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    marinaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlipDto"][];
                        "application/json": components["schemas"]["SlipDto"][];
                        "text/json": components["schemas"]["SlipDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    marinaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSlipRequest"];
                    "text/json": components["schemas"]["CreateSlipRequest"];
                    "application/*+json": components["schemas"]["CreateSlipRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marinas/{marinaId}/slips/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    boatLength?: number | string;
                    boatBeam?: number | string;
                    boatDraft?: number | string;
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path: {
                    marinaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlipDto"][];
                        "application/json": components["schemas"]["SlipDto"][];
                        "text/json": components["schemas"]["SlipDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSlipRequest"];
                    "text/json": components["schemas"]["UpdateSlipRequest"];
                    "application/*+json": components["schemas"]["UpdateSlipRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteStaffCommand"];
                    "text/json": components["schemas"]["InviteStaffCommand"];
                    "application/*+json": components["schemas"]["InviteStaffCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InviteStaffResult"];
                        "application/json": components["schemas"]["InviteStaffResult"];
                        "text/json": components["schemas"]["InviteStaffResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TenantDto"][];
                        "application/json": components["schemas"]["TenantDto"][];
                        "text/json": components["schemas"]["TenantDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTenantCommand"];
                    "text/json": components["schemas"]["CreateTenantCommand"];
                    "application/*+json": components["schemas"]["CreateTenantCommand"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateTenantResult"];
                        "application/json": components["schemas"]["CreateTenantResult"];
                        "text/json": components["schemas"]["CreateTenantResult"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTenantRequest"];
                    "text/json": components["schemas"]["UpdateTenantRequest"];
                    "application/*+json": components["schemas"]["UpdateTenantRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressDto: {
            street: string;
            city: string;
            state: string;
            zip: string;
            country: string;
        };
        AssignmentType: number;
        BoatDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerAccountId: string;
            name: string;
            make: null | string;
            model: null | string;
            /** Format: int32 */
            year: null | number | string;
            /** Format: double */
            length: number | string;
            /** Format: double */
            beam: number | string;
            /** Format: double */
            draft: number | string;
            boatType: components["schemas"]["BoatType"];
            hullColor: null | string;
            registrationNumber: null | string;
            registrationState: null | string;
            insuranceProvider: null | string;
            insurancePolicyNumber: null | string;
            /** Format: date */
            insuranceExpiresOn: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        BoatType: number;
        CreateBoatRequest: {
            name: string;
            make: null | string;
            model: null | string;
            /** Format: int32 */
            year: null | number | string;
            /** Format: double */
            length: number | string;
            /** Format: double */
            beam: number | string;
            /** Format: double */
            draft: number | string;
            boatType: components["schemas"]["BoatType"];
            hullColor: null | string;
            registrationNumber: null | string;
            registrationState: null | string;
            insuranceProvider: null | string;
            insurancePolicyNumber: null | string;
            /** Format: date */
            insuranceExpiresOn: null | string;
        };
        CreateCustomerAccountCommand: {
            displayName: string;
            billingEmail: string;
            billingPhone: null | string;
            billingAddress: null | components["schemas"]["AddressDto"];
            emergencyContactName: null | string;
            emergencyContactPhone: null | string;
            notes: null | string;
        };
        CreateDockRequest: {
            name: string;
            description: null | string;
            /**
             * Format: int32
             * @default 0
             */
            sortOrder: number | string;
        };
        CreateMarinaCommand: {
            name: string;
            address: components["schemas"]["AddressDto"];
            phoneNumber: string;
            email: string;
            timeZoneId: string;
            website: null | string;
            description: null | string;
        };
        CreateSlipAssignmentCommand: {
            /** Format: uuid */
            slipId: string;
            /** Format: uuid */
            customerAccountId: string;
            /** Format: uuid */
            boatId: string;
            assignmentType: components["schemas"]["AssignmentType"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            /** Format: double */
            rateOverride: null | number | string;
            notes: null | string;
        };
        CreateSlipRequest: {
            /** Format: uuid */
            dockId: null | string;
            name: string;
            slipType: components["schemas"]["SlipType"];
            /** Format: double */
            maxLength: number | string;
            /** Format: double */
            maxBeam: number | string;
            /** Format: double */
            maxDraft: number | string;
            hasElectric: boolean;
            electric: null | components["schemas"]["ElectricService"];
            hasWater: boolean;
            rateType: components["schemas"]["RateType"];
            /** Format: double */
            dailyRate: null | number | string;
            /** Format: double */
            monthlyRate: null | number | string;
            /** Format: double */
            annualRate: null | number | string;
            status: components["schemas"]["SlipStatus"];
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            notes: null | string;
        };
        CreateTenantCommand: {
            name: string;
            slug: string;
            ownerEmail: string;
            ownerFirstName: string;
            ownerLastName: string;
            ownerPassword: string;
            subscriptionTier?: components["schemas"]["SubscriptionTier"];
        };
        CreateTenantResult: {
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            ownerId: string;
        };
        CustomerAccountDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            billingEmail: string;
            billingPhone: null | string;
            billingAddress: null | components["schemas"]["AddressDto"];
            emergencyContactName: null | string;
            emergencyContactPhone: null | string;
            notes: null | string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        DockDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            marinaId: string;
            name: string;
            description: null | string;
            /** Format: int32 */
            sortOrder: number | string;
            /** Format: date-time */
            createdAt: string;
        };
        ElectricService: number;
        EndAssignmentRequest: {
            /** Format: date */
            endDate: string;
        };
        InviteStaffCommand: {
            /** Format: uuid */
            marinaId: string;
            email: string;
            firstName: string;
            lastName: string;
            role: components["schemas"]["UserRole"];
        };
        InviteStaffResult: {
            /** Format: uuid */
            userId: string;
            temporaryPassword: string;
        };
        LoginCommand: {
            email: string;
            password: string;
        };
        LoginResult: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            userId: string;
            email: string;
            firstName: string;
            lastName: string;
            role: components["schemas"]["UserRole"];
            /** Format: uuid */
            tenantId: null | string;
            /** Format: uuid */
            marinaId: null | string;
        };
        MarinaDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            name: string;
            address: components["schemas"]["AddressDto"];
            phoneNumber: string;
            email: string;
            timeZoneId: string;
            website: null | string;
            description: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RateType: number;
        SlipAssignmentDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            slipId: string;
            slipName: string;
            /** Format: uuid */
            customerAccountId: string;
            customerDisplayName: string;
            /** Format: uuid */
            boatId: string;
            boatName: string;
            assignmentType: components["schemas"]["AssignmentType"];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            /** Format: double */
            rateOverride: null | number | string;
            notes: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        SlipDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            marinaId: string;
            /** Format: uuid */
            dockId: null | string;
            name: string;
            slipType: components["schemas"]["SlipType"];
            /** Format: double */
            maxLength: number | string;
            /** Format: double */
            maxBeam: number | string;
            /** Format: double */
            maxDraft: number | string;
            hasElectric: boolean;
            electric: null | components["schemas"]["ElectricService"];
            hasWater: boolean;
            rateType: components["schemas"]["RateType"];
            /** Format: double */
            dailyRate: null | number | string;
            /** Format: double */
            monthlyRate: null | number | string;
            /** Format: double */
            annualRate: null | number | string;
            status: components["schemas"]["SlipStatus"];
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            notes: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        SlipStatus: number;
        SlipType: number;
        SubscriptionTier: number;
        TenantDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            isActive: boolean;
            subscriptionTier: components["schemas"]["SubscriptionTier"];
            /** Format: date-time */
            createdAt: string;
        };
        UpdateBoatRequest: {
            name: string;
            make: null | string;
            model: null | string;
            /** Format: int32 */
            year: null | number | string;
            /** Format: double */
            length: number | string;
            /** Format: double */
            beam: number | string;
            /** Format: double */
            draft: number | string;
            boatType: components["schemas"]["BoatType"];
            hullColor: null | string;
            registrationNumber: null | string;
            registrationState: null | string;
            insuranceProvider: null | string;
            insurancePolicyNumber: null | string;
            /** Format: date */
            insuranceExpiresOn: null | string;
        };
        UpdateCustomerRequest: {
            displayName: string;
            billingEmail: string;
            billingPhone: null | string;
            billingAddress: null | components["schemas"]["AddressDto"];
            emergencyContactName: null | string;
            emergencyContactPhone: null | string;
            notes: null | string;
        };
        UpdateDockRequest: {
            name: string;
            description: null | string;
            /** Format: int32 */
            sortOrder: number | string;
        };
        UpdateMarinaRequest: {
            name: string;
            address: components["schemas"]["AddressDto"];
            phoneNumber: string;
            email: string;
            timeZoneId: string;
            website: null | string;
            description: null | string;
        };
        UpdateSlipRequest: {
            name: string;
            slipType: components["schemas"]["SlipType"];
            /** Format: double */
            maxLength: number | string;
            /** Format: double */
            maxBeam: number | string;
            /** Format: double */
            maxDraft: number | string;
            hasElectric: boolean;
            electric: null | components["schemas"]["ElectricService"];
            hasWater: boolean;
            rateType: components["schemas"]["RateType"];
            /** Format: double */
            dailyRate: null | number | string;
            /** Format: double */
            monthlyRate: null | number | string;
            /** Format: double */
            annualRate: null | number | string;
            status: components["schemas"]["SlipStatus"];
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            notes: null | string;
        };
        UpdateTenantRequest: {
            name: string;
            isActive: boolean;
            subscriptionTier: components["schemas"]["SubscriptionTier"];
        };
        UserRole: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
