{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mymarina.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mymarina.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.appHost | quote }}
        - {{ .Values.ingress.apiHost | quote }}
        {{- if .Values.marketing.enabled }}
        - {{ .Values.ingress.marketingHost | quote }}
        - {{ printf "www.%s" .Values.ingress.marketingHost | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.appHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mymarina.webui.name" . }}
                port:
                  number: {{ .Values.webui.port }}
    - host: {{ .Values.ingress.apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mymarina.api.name" . }}
                port:
                  number: {{ .Values.api.port }}
    {{- if .Values.marketing.enabled }}
    - host: {{ .Values.ingress.marketingHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mymarina.marketing.name" . }}
                port:
                  number: 80
    - host: {{ printf "www.%s" .Values.ingress.marketingHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mymarina.marketing.name" . }}
                port:
                  number: 80
    {{- end }}
{{- end }}
