apiVersion: v1
kind: Service
metadata:
  name: {{ include "mymarina.api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mymarina.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "mymarina.api.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
