apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mymarina.webui.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mymarina.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  replicas: {{ .Values.webui.replicaCount }}
  selector:
    matchLabels:
      {{- include "mymarina.webui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mymarina.webui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"
          imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webui.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
          {{- with .Values.webui.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
